services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=veterinary'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=dbcAdmin'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: "postgres_data"